name    'coralnexus-ntp'
version '0.4.0'
source 'git://github.com/coralnexus/puppet-ntp'
author 'Coral Nexus'
license 'Apache Version 2.0'
summary 'NTP Module'
description 'NTP Module for Debian and eventually other systems.'
project_page 'http://github.com/coralnexus/puppet-ntp'
dependency 'coralnexus/corl', '>= 0.4.0'
